# Generated by Django 6.0.3 on 2026-05-16 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Aktif'), ('COMPLETED', 'Selesai'), ('DROPPED', 'Keluar')], db_index=True, default='ACTIVE', max_length=10)),
                ('price_at_enrollment', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='academics.kelas')),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='accounts.studentprofile')),
            ],
            options={
                'verbose_name': 'Pendaftaran',
                'verbose_name_plural': 'Pendaftaran',
                'indexes': [models.Index(fields=['student_profile'], name='enrollments_student_6b39ae_idx'), models.Index(fields=['kelas'], name='enrollments_kelas_i_f4bca3_idx'), models.Index(fields=['status'], name='enrollments_status_48622c_idx')],
                'unique_together': {('student_profile', 'kelas')},
            },
        ),
    ]
