# Generated by Django 6.0.3 on 2026-05-18 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_kelas_level'),
        ('accounts', '0002_remove_teacherprofile_teaches_sd_and_more'),
        ('enrollments', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('student_profile', 'kelas'), name='uniq_enrollment_student_kelas'),
        ),
    ]
