# Generated by Django 6.0.3 on 2026-05-19 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_backfill_subject_icons'),
        ('accounts', '0002_remove_teacherprofile_teaches_sd_and_more'),
        ('enrollments', '0002_alter_enrollment_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentWaitlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(help_text='Posisi antrian (mulai dari 1)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notified_at', models.DateTimeField(blank=True, help_text='Kapan student dinotif slot kosong (NULL = belum dinotif).', null=True)),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlists', to='academics.kelas')),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlists', to='accounts.studentprofile')),
            ],
            options={
                'verbose_name': 'Waitlist',
                'verbose_name_plural': 'Waitlist',
                'ordering': ['kelas', 'position'],
                'indexes': [models.Index(fields=['kelas', 'position'], name='enrollments_kelas_i_39af1f_idx')],
                'constraints': [models.UniqueConstraint(fields=('student_profile', 'kelas'), name='unique_waitlist_student_kelas')],
            },
        ),
    ]
