# Generated by Django 6.0.3 on 2026-04-02 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_number', models.PositiveSmallIntegerField()),
                ('date', models.DateField(db_index=True)),
                ('topic', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Terjadwal'), ('COMPLETED', 'Selesai'), ('CANCELLED', 'Dibatalkan')], default='SCHEDULED', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='academics.kelas')),
            ],
            options={
                'verbose_name': 'Sesi',
                'verbose_name_plural': 'Sesi',
                'ordering': ['kelas', 'session_number'],
                'indexes': [models.Index(fields=['kelas'], name='sessions_ap_kelas_i_ce47fa_idx'), models.Index(fields=['date'], name='sessions_ap_date_11f219_idx')],
                'unique_together': {('kelas', 'session_number')},
            },
        ),
    ]
