# Generated by Django 6.0.3 on 2026-05-16 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('enrollments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_number', models.PositiveSmallIntegerField()),
                ('date', models.DateField(db_index=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('topic', models.CharField(blank=True, max_length=300)),
                ('capacity', models.PositiveSmallIntegerField(default=0)),
                ('session_type', models.CharField(choices=[('REGULAR', 'Reguler'), ('MAKEUP', 'Pengganti'), ('OPTIONAL', 'Opsional')], default='REGULAR', max_length=10)),
                ('meeting_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Terjadwal'), ('COMPLETED', 'Selesai'), ('CANCELLED', 'Dibatalkan')], default='SCHEDULED', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='academics.kelas')),
            ],
            options={
                'verbose_name': 'Sesi',
                'verbose_name_plural': 'Sesi',
                'ordering': ['kelas', 'session_number'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PRESENT', 'Hadir'), ('PERMITTED', 'Izin'), ('ABSENT', 'Alpha')], default='PRESENT', max_length=10)),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='enrollments.enrollment')),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_attendances', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='sessions_app.session')),
            ],
            options={
                'verbose_name': 'Kehadiran',
                'verbose_name_plural': 'Kehadiran',
            },
        ),
        migrations.CreateModel(
            name='SessionBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('BOOKED', 'Terdaftar'), ('CANCELLED', 'Dibatalkan')], default='BOOKED', max_length=10)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_bookings', to='enrollments.enrollment')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='sessions_app.session')),
            ],
            options={
                'verbose_name': 'Booking Pertemuan',
                'verbose_name_plural': 'Booking Pertemuan',
            },
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['kelas'], name='sessions_ap_kelas_i_ce47fa_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['date'], name='sessions_ap_date_11f219_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='session',
            unique_together={('kelas', 'session_number')},
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['enrollment'], name='sessions_ap_enrollm_b872b4_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['session'], name='sessions_ap_session_04f2dd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('enrollment', 'session')},
        ),
        migrations.AddIndex(
            model_name='sessionbooking',
            index=models.Index(fields=['enrollment'], name='sessions_ap_enrollm_7fd23c_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionbooking',
            index=models.Index(fields=['session'], name='sessions_ap_session_45c317_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sessionbooking',
            unique_together={('enrollment', 'session')},
        ),
    ]
