# Generated by Django 6.0.3 on 2026-05-30 21:30
# Phase 3R schema unlock: SessionBooking becomes the universal session-level
# enrollment record (all session types). Adds kind, soft-delete fields, +
# a data step that backfills historical rows as kind='MAKEUP' (since pre-unlock
# the table was only used for MAKEUP/OPTIONAL bookings).

from django.db import migrations, models


def backfill_historical_kind_makeup(apps, schema_editor):
    """All existing SessionBooking rows pre-unlock were MAKEUP/OPTIONAL flow.
    Set kind='MAKEUP' for them so the AUTO/PICKED labels stay meaningful for
    rows seeded post-unlock. Idempotent: only flips rows still at the default.
    """
    SessionBooking = apps.get_model('sessions_app', 'SessionBooking')
    SessionBooking.objects.filter(kind='PICKED').update(kind='MAKEUP')


def noop(apps, schema_editor):
    """Reverse is a no-op — we don't try to un-tag MAKEUP back to PICKED."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0003_enrollmentwaitlist'),
        ('sessions_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionbooking',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionbooking',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sessionbooking',
            name='kind',
            field=models.CharField(
                choices=[('AUTO', 'Otomatis'), ('PICKED', 'Dipilih'), ('MAKEUP', 'Susulan')],
                db_index=True, default='PICKED', max_length=10,
            ),
        ),
        migrations.AddIndex(
            model_name='sessionbooking',
            index=models.Index(fields=['kind'], name='sessions_ap_kind_90df0d_idx'),
        ),
        migrations.RunPython(backfill_historical_kind_makeup, reverse_code=noop),
    ]
