# Generated by Django 6.0.3 on 2026-04-18 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0001_initial'),
        ('sessions_app', '0002_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='capacity',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='SessionBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('BOOKED', 'Terdaftar'), ('CANCELLED', 'Dibatalkan')], default='BOOKED', max_length=10)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_bookings', to='enrollments.enrollment')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='sessions_app.session')),
            ],
            options={
                'verbose_name': 'Booking Pertemuan',
                'verbose_name_plural': 'Booking Pertemuan',
                'indexes': [models.Index(fields=['enrollment'], name='sessions_ap_enrollm_7fd23c_idx'), models.Index(fields=['session'], name='sessions_ap_session_45c317_idx')],
                'unique_together': {('enrollment', 'session')},
            },
        ),
    ]
