# Generated by Django 6.0.3 on 2026-05-01 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_app', '0003_session_capacity_sessionbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
