# Generated by Django 6.0.3 on 2026-05-16 18:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('enrollments', '0001_initial'),
        ('sessions_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_type', models.CharField(choices=[('QUIZ', 'Kuis'), ('MIDTERM', 'UTS'), ('FINAL', 'UAS'), ('ASSIGNMENT', 'Tugas')], max_length=12)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('graded_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='enrollments.enrollment')),
                ('graded_by_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_entries', to='accounts.teacherprofile')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grades', to='sessions_app.session')),
            ],
            options={
                'verbose_name': 'Nilai',
                'verbose_name_plural': 'Nilai',
                'ordering': ['enrollment', 'grade_type', '-graded_at'],
                'indexes': [models.Index(fields=['enrollment'], name='grades_grad_enrollm_05f67c_idx'), models.Index(fields=['session'], name='grades_grad_session_2a224a_idx')],
            },
        ),
    ]
