# Generated by Django 6.0.3 on 2026-05-17 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherprofile',
            name='teaches_sd',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='teaches_sma',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='teaches_smp',
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='level',
            field=models.CharField(blank=True, choices=[('TK', 'TK'), ('SD', 'SD'), ('SMP', 'SMP'), ('SMA', 'SMA'), ('UMUM', 'Umum')], max_length=5),
        ),
        migrations.CreateModel(
            name='TeacherJenjang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('TK', 'TK'), ('SD', 'SD'), ('SMP', 'SMP'), ('SMA', 'SMA'), ('UMUM', 'Umum')], max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('teacher_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jenjang_set', to='accounts.teacherprofile')),
            ],
            options={
                'verbose_name': 'Jenjang Guru',
                'verbose_name_plural': 'Jenjang Guru',
                'ordering': ['teacher_profile_id', 'level'],
                'unique_together': {('teacher_profile', 'level')},
            },
        ),
    ]
