# Generated by Django 6.0.3 on 2026-05-03 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_teacherprofile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='teaches_sd',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='teaches_sma',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='teaches_smp',
            field=models.BooleanField(default=False),
        ),
    ]
