# Generated by Django 6.0.3 on 2026-05-16 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('sessions_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='course_materials/%Y/%m/')),
                ('file_type', models.CharField(blank=True, choices=[('PDF', 'PDF'), ('IMAGE', 'Gambar'), ('VIDEO', 'Video'), ('DOC', 'Dokumen'), ('OTHER', 'Lainnya')], default='OTHER', max_length=10)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='academics.kelas')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='sessions_app.session')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_materials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Materi Pembelajaran',
                'verbose_name_plural': 'Materi Pembelajaran',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['kelas'], name='course_mate_kelas_i_af1380_idx')],
            },
        ),
    ]
