# Generated by Django 6.0.3 on 2026-05-16 18:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('enrollments', '0001_initial'),
        ('sessions_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('year', models.PositiveSmallIntegerField()),
                ('summary', models.TextField()),
                ('topics_covered', models.TextField()),
                ('strengths', models.TextField()),
                ('areas_for_improvement', models.TextField()),
                ('viewed_by_parent', models.BooleanField(default=False)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('parent_response', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_journals', to='enrollments.enrollment')),
                ('written_by_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_journals_written', to='accounts.teacherprofile')),
            ],
            options={
                'verbose_name': 'Jurnal Bulanan',
                'verbose_name_plural': 'Jurnal Bulanan',
                'ordering': ['-year', '-month'],
                'indexes': [models.Index(fields=['enrollment'], name='journals_mo_enrollm_d4f2a1_idx'), models.Index(fields=['year', 'month'], name='journals_mo_year_d1e50b_idx')],
                'unique_together': {('enrollment', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='SessionNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('BEHAVIOR', 'Perilaku'), ('UNDERSTANDING', 'Pemahaman'), ('PARTICIPATION', 'Partisipasi'), ('GENERAL', 'Umum')], default='GENERAL', max_length=15)),
                ('content', models.TextField()),
                ('visibility', models.CharField(choices=[('TEACHER_ONLY', 'Hanya Guru'), ('VISIBLE_TO_PARENT', 'Terlihat Orang Tua')], default='TEACHER_ONLY', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_notes', to='enrollments.enrollment')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='sessions_app.session')),
                ('written_by_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_notes_written', to='accounts.teacherprofile')),
            ],
            options={
                'verbose_name': 'Catatan Sesi',
                'verbose_name_plural': 'Catatan Sesi',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session', 'enrollment'], name='journals_se_session_09e149_idx')],
            },
        ),
    ]
