# Generated by Django 6.0.3 on 2026-03-29 21:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategori',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AcademicPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10)),
                ('quarter', models.CharField(choices=[('Q1', 'Kuartal 1'), ('Q2', 'Kuartal 2'), ('Q3', 'Kuartal 3'), ('Q4', 'Kuartal 4')], max_length=2)),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Periode Akademik',
                'verbose_name_plural': 'Periode Akademik',
                'ordering': ['-year', 'quarter'],
                'unique_together': {('year', 'quarter')},
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='academics.category')),
            ],
            options={
                'verbose_name': 'Mata Pelajaran',
                'verbose_name_plural': 'Mata Pelajaran',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('level', models.CharField(choices=[('SD', 'SD'), ('SMP', 'SMP'), ('SMA', 'SMA')], max_length=5)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('capacity', models.PositiveSmallIntegerField()),
                ('total_sessions', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('OPEN', 'Buka'), ('FULL', 'Penuh'), ('CLOSED', 'Tutup')], default='OPEN', max_length=10)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='academics.academicperiod')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'TEACHER'}, on_delete=django.db.models.deletion.PROTECT, related_name='taught_classes', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='academics.subject')),
            ],
            options={
                'verbose_name': 'Kelas',
                'verbose_name_plural': 'Kelas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('MONDAY', 'Senin'), ('TUESDAY', 'Selasa'), ('WEDNESDAY', 'Rabu'), ('THURSDAY', 'Kamis'), ('FRIDAY', 'Jumat'), ('SATURDAY', 'Sabtu')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('room', models.CharField(blank=True, max_length=100)),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='academics.kelas')),
            ],
            options={
                'verbose_name': 'Jadwal',
                'verbose_name_plural': 'Jadwal',
                'indexes': [models.Index(fields=['kelas'], name='academics_s_kelas_i_a0af4a_idx')],
                'unique_together': {('kelas', 'day', 'start_time')},
            },
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['category'], name='academics_s_categor_43cc54_idx'),
        ),
        migrations.AddIndex(
            model_name='kelas',
            index=models.Index(fields=['teacher'], name='academics_k_teacher_f8fcce_idx'),
        ),
        migrations.AddIndex(
            model_name='kelas',
            index=models.Index(fields=['subject'], name='academics_k_subject_2134e3_idx'),
        ),
        migrations.AddIndex(
            model_name='kelas',
            index=models.Index(fields=['academic_period'], name='academics_k_academi_2b8973_idx'),
        ),
        migrations.AddIndex(
            model_name='kelas',
            index=models.Index(fields=['status'], name='academics_k_status_b9bb7e_idx'),
        ),
    ]
