# Generated by Django 6.0.3 on 2026-05-16 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kelas',
            name='teacher_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='taught_classes', to='accounts.teacherprofile'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='kelas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='academics.kelas'),
        ),
        migrations.AddField(
            model_name='subject',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='academics.category'),
        ),
        migrations.AddField(
            model_name='kelas',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='academics.subject'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['kelas'], name='academics_s_kelas_i_a0af4a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('kelas', 'day', 'start_time')},
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['category'], name='academics_s_categor_43cc54_idx'),
        ),
        migrations.AddIndex(
            model_name='kelas',
            index=models.Index(fields=['teacher_profile'], name='academics_k_teacher_b09ca9_idx'),
        ),
        migrations.AddIndex(
            model_name='kelas',
            index=models.Index(fields=['subject'], name='academics_k_subject_2134e3_idx'),
        ),
        migrations.AddIndex(
            model_name='kelas',
            index=models.Index(fields=['academic_period'], name='academics_k_academi_2b8973_idx'),
        ),
        migrations.AddIndex(
            model_name='kelas',
            index=models.Index(fields=['status'], name='academics_k_status_b9bb7e_idx'),
        ),
    ]
