# Generated by Django 6.0.3 on 2026-05-17 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kelas',
            name='level',
            field=models.CharField(choices=[('TK', 'TK'), ('SD', 'SD'), ('SMP', 'SMP'), ('SMA', 'SMA'), ('UMUM', 'Umum')], max_length=5),
        ),
    ]
