# Generated by Django 6.0.3 on 2026-05-18 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_kelas_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='icon',
            field=models.CharField(blank=True, default='', help_text='Optional emoji shown on the class card. Falls back to subject_emoji filter.', max_length=10),
        ),
    ]
