# Generated by Django 6.0.3 on 2026-06-06 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_backfill_subject_icons'),
    ]

    operations = [
        migrations.AddField(
            model_name='kelas',
            name='class_type',
            field=models.CharField(choices=[('REGULAR', 'Reguler'), ('GANJIL_GENAP', 'Paket Ganjil Genap')], default='REGULAR', help_text='REGULAR (default) atau GANJIL_GENAP (paket dua kursi, satu ganjil, satu genap).', max_length=15),
        ),
        migrations.CreateModel(
            name='KelasJenjang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('TK', 'TK'), ('SD', 'SD'), ('SMP', 'SMP'), ('SMA', 'SMA'), ('UMUM', 'Umum')], max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jenjang_set', to='academics.kelas')),
            ],
            options={
                'verbose_name': 'Jenjang Kelas',
                'verbose_name_plural': 'Jenjang Kelas',
                'ordering': ['kelas_id', 'level'],
                'unique_together': {('kelas', 'level')},
            },
        ),
    ]
