# Generated by Django 6.0.3 on 2026-06-07 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_backfill_kelas_jenjang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kelas',
            name='class_type',
            field=models.CharField(choices=[('PRIVAT', 'Privat'), ('GROUP', 'Grup'), ('GANJIL_GENAP', 'Paket Ganjil Genap')], default='GROUP', help_text='PRIVAT (kapasitas 1), GROUP (kapasitas dipilih guru), atau GANJIL_GENAP (dua kursi, satu ganjil + satu genap, window 2N minggu).', max_length=15),
        ),
    ]
